server:
  port: 9090
spring:
  application:
    name: cloud-order-service

  #P94 需要的配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  #采样率值介于0-1之间,1标识全部采集

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:7002/eureka/  #单机版
  #       defaultZone: http://localhost.com:7001/eureka/,http://localhost:7002/eureka/ #集群版

  instance:
    instance-id: order9090
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔.单位为秒(默认30 秒)
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳等待时间上限.单位为秒(默认90 秒),超时将剔除服务
    lease-expiration-duration-in-seconds: 90